# Generated by Django 3.2.4 on 2021-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='account',
        ),
    ]
