# Generated by Django 3.2.4 on 2021-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_account'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
